POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "title": "My First Blog Post",
  "content": "This is the content of my first blog post.",
  "category": "Technology",
  "tags": ["Tech", "Programming"]
}
//{
//  "id": 2,
//  "title": "My Second Blog Post",
//  "content": "This is the content of my second blog post.",
//  "category": "Technology",
//  "tags": ["Tech", "Programming"],
//  "createdAt": "2021-09-01T12:30:00Z",
//  "updatedAt": "2021-09-01T12:30:00Z"
//}